/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type { import('@docusaurus/plugin-content-docs').SidebarsConfig } */
const sidebars = {
  tutorialSidebar: [{"type": "autogenerated", "dirName": "."}],
    tutorialSidebar: [
    [{'type': 'category', 'label': 'architecture', 'items': ['architecture/architecture']}, {'type': 'category', 'label': 'blog', 'items': ['blog/2019-05-28-first-blog-post']}, {'type': 'category', 'label': 'blog', 'items': ['blog/2019-05-29-long-blog-post']}, {'type': 'category', 'label': '2021-08-26-welcome', 'items': ['blog/2021-08-26-welcome/index']}, {'type': 'category', 'label': 'device-management', 'items': ['device-management/device-management']}, {'type': 'category', 'label': 'join-rdk', 'items': ['join-rdk/join-rdk']}, {'type': 'category', 'label': 'my-documentation', 'items': ['my-documentation/README']}, {'type': 'category', 'label': 'architecture', 'items': ['my-documentation/docs/architecture/architecture']}, {'type': 'category', 'label': 'device-management', 'items': ['my-documentation/docs/device-management/device-management']}, {'type': 'category', 'label': 'architecture', 'items': ['my-documentation/versioned_docs/version-0.1.0/architecture/architecture']}, {'type': 'category', 'label': 'device-management', 'items': ['my-documentation/versioned_docs/version-0.1.0/device-management/device-management']}, {'type': 'category', 'label': 'pages', 'items': ['pages/markdown-page']}]
  ],
};

export default sidebars;
